export const initialMarathons = [
  {
    id: "marathon-june",
    month: "june",
    title_ka: "ივნისის მარათონი",
    title_en: "June Marathon",
    startDate: "2026-06-01T00:00:00+04:00",
    endDate: "2026-06-30T18:00:00+04:00",
    timezone: "Asia/Tbilisi",
    status: "active",
    challenges: [],
    aiGenerated: false,
    approvedByAdmin: true,
    createdAt: "2026-06-01T12:00:00Z"
  },
  {
    id: "marathon-july",
    month: "july",
    title_ka: "ივლისის მარათონი",
    title_en: "July Marathon",
    startDate: "2026-07-01T00:00:00+04:00",
    endDate: "2026-07-30T18:00:00+04:00",
    timezone: "Asia/Tbilisi",
    status: "upcoming",
    challenges: [],
    aiGenerated: false,
    approvedByAdmin: true,
    createdAt: "2026-06-01T12:00:00Z"
  },
  {
    id: "marathon-august",
    month: "august",
    title_ka: "აგვისტოს მარათონი",
    title_en: "August Marathon",
    startDate: "2026-08-01T00:00:00+04:00",
    endDate: "2026-08-30T18:00:00+04:00",
    timezone: "Asia/Tbilisi",
    status: "upcoming",
    challenges: [],
    aiGenerated: false,
    approvedByAdmin: true,
    createdAt: "2026-06-01T12:00:00Z"
  },
  {
    id: "marathon-september",
    month: "september",
    title_ka: "სექტემბრის მარათონი",
    title_en: "September Marathon",
    startDate: "2026-09-01T00:00:00+04:00",
    endDate: "2026-09-30T18:00:00+04:00",
    timezone: "Asia/Tbilisi",
    status: "upcoming",
    challenges: [],
    aiGenerated: false,
    approvedByAdmin: true,
    createdAt: "2026-06-01T12:00:00Z"
  }
];

export const initialAvailableSlots = [
  { id: "slot-1", date: "2026-06-05", time: "12:00", status: "available" },
  { id: "slot-2", date: "2026-06-05", time: "12:30", status: "available" },
  { id: "slot-3", date: "2026-06-06", time: "15:00", status: "available" },
  { id: "slot-4", date: "2026-06-10", time: "18:00", status: "available" },
  { id: "slot-5", date: "2026-06-12", time: "11:00", status: "available" },
  { id: "slot-6", date: "2026-06-15", time: "14:00", status: "available" },
  { id: "slot-7", date: "2026-06-20", time: "16:30", status: "available" }
];

export const initialChallenges = [
  // ================= JUNE CHALLENGES (10) =================
  {
    id: "ch-june-1",
    marathonId: "marathon-june",
    challengeNumber: 1,
    title: "ჩემი ახალი მეგობარი—მესაიდუმლე",
    title_en: "My New Confidant Friend",
    description: "ჩაწერე 1-წუთიანი ვიდეო, სადაც წარადგენ საკუთარ თავს გამოგონილი საიდუმლო სახელით და გაგვიზიარებ 3 შენს კარგ თვისებას.",
    description_en: "Record a 1-minute video introducing yourself with your fictional nickname and sharing 3 good qualities.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "დაჯექი კამერის წინ, გაიღიმე, დაასახელე შენი თამაშის სახელი (ნიკნეიმი). აუხსენი სხვა მოთამაშეებს, რატომ შეარჩიე ეს სახელი და რა არის ის 3 თვისება, რომელიც შენში ყველაზე მეტად მოგწონს. ეს დაგეხმარება საკუთარი თავის პოზიტიურად მიღებაში.",
    fullInstructions_en: "Sit in front of the camera, smile, and say your in-game nickname. Explain to other players why you chose it and what three qualities you like most about yourself.",
    safetyRules: "არ გაამჟღავნო შენი ზუსტი საცხოვრებელი ადგილი ან პირადი საიდუმლო ინფორმაცია, რომელიც შეიძლება არასასურველად იქნას გამოყენებული.",
    safetyRules_en: "Do not reveal your exact location or private/sensitive information that could be used maliciously.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რა იგრძენი შენი საუკეთესო თვისებების ხმამაღლა წარმოთქმისას?",
    reflectionQuestion_en: "How did it feel to express your best features aloud?",
    personalDevelopmentReason: "თვითშეფასების გაუმჯობესება პოზიტიური აფირმაციის გზით.",
    personalDevelopmentReason_en: "Improving self-esteem through positive self-talk."
  },
  {
    id: "ch-june-2",
    marathonId: "marathon-june",
    challengeNumber: 2,
    title: "სარკის წინაშე აღიარება",
    title_en: "Mirror Confession",
    description: "სარკეში ყურებისას უთხარი საკუთარ თავს სამი გულახდილი და თბილი კომპლიმენტი. გადაიღე ეს პროცესი.",
    description_en: "Look in the mirror and tell yourself three honest, warm compliments. Record this process.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "მიდი სარკესთან, ჩართე კამერა, შეხედე შენს თვალებს და ხმამაღლა, მკაფიოდ უთხარი საკუთარ თავს 3 კომპლიმენტი. მაგალითად: 'მე ვამაყობ შენი ნიჭით', 'შენ ხარ ძალიან თბილი ადამიანი'. გაიღიმე და დაასრულე ჩანაწერი.",
    fullInstructions_en: "Go to the mirror, turn on the camera, look into your own eyes, and speak three compliments aloud clearly. For example: 'I am proud of your talent', 'You are a warm person'.",
    safetyRules: "არავითარი კრიტიკა ან სირცხვილის გრძნობა — მხოლოდ პოზიტიური და თბილი სიტყვები. პროცესი უნდა იყოს აბსოლუტურად კომფორტული შენთვის.",
    safetyRules_en: "No self-criticism or shame allowed — only positive, warm words. The process must feel absolutely comfortable for you.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 2,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 15,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 15,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გრძნობდი თუ არა უხერხულობას სარკეში ყურებისას?",
    reflectionQuestion_en: "Did you feel awkward looking in the mirror?",
    personalDevelopmentReason: "საკუთარ თავთან სიახლოვისა და პოზიტიური დამოკიდებულების გაძლიერება.",
    personalDevelopmentReason_en: "Strengthening intimacy and positive configuration with oneself."
  },
  {
    id: "ch-june-3",
    marathonId: "marathon-june",
    challengeNumber: 3,
    title: "ექსცენტრული კოსტიუმი სახლში",
    title_en: "Eccentric Costume at Home",
    description: "ჩაიცვი რაღაც უცნაური ან ფერადი, რაც აქამდე არასდროს ჩაგიცვამს (თუნდაც საბანი კაპიუშონად) და ახსენი შენი განწყობა.",
    description_en: "Put on something unusual or colorful that you've never worn before (even a blanket as a hood) and explain your mood.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "მოიძიე სახლში ფერადი ტანსაცმელი, გააკეთე უჩვეულო კომბინაცია ან მოირგე საოჯახო ნივთები 'გმირის კოსტიუმად'. გადაიღე 30-წამიანი განმარტება, თუ როგორ გეხმარება ეს იმიჯი შინაგანი თავისუფლების გამოხატვაში.",
    fullInstructions_en: "Find some colorful clothes at home, create a unique combination or wear household items as a helper's theme costume. Record a 30-second video explaining how this look helps you express your inner freedom.",
    safetyRules: "გამოწვევა სრულდება მხოლოდ სახლში, უსაფრთხო გარემოში. არ გამოიყენო ნივთები, რომლებიც დაგაზიანებს.",
    safetyRules_en: "The challenge should only be performed inside your home in a safe environment. Do not use items that could harm you.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 20,
    completionReward: 40,
    publicBraveryBonus: 20,
    points: 40,
    acceptanceCost: 20,
    skipCost: 5,
    publicVideoBonus: 20,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "დაგეხმარა თუ არა კოსტიუმის ჩაცმა შინაგანი ბარიერის მოხსნაში?",
    reflectionQuestion_en: "Did wearing the costume help you lower your inner barriers?",
    personalDevelopmentReason: "კრეატიულობის გაძლიერება და დუმილის ზონის გაფართოება.",
    personalDevelopmentReason_en: "Boosting creativity and expanding the boundaries of comfort."
  },
  {
    id: "ch-june-4",
    marathonId: "marathon-june",
    challengeNumber: 4,
    title: "მადლიერების 5 საგანი",
    title_en: "5 Items of Gratitude",
    description: "გამოავლინე და აჩვენე სახლში არსებული 5 ნივთი, რომლებიც შენს ხასიათს საუკეთესოდ აღწერს.",
    description_en: "Find and show 5 items in your home that best represent your personality.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "მოაწყე სწრაფი ძიება. აარჩიე 5 ნივთი (მაგალითად: საყვარელი წიგნი, კათხა, ძველი სუვენირი, მცენარე, სათამაშო). გადაიღე ვიდეო ან დაწერე რეფლექსია იმაზე, თუ როგორ ირეკლავს თითოეული ნივთი შენს ინდივიდუალურობას.",
    fullInstructions_en: "Search your home. Choose 5 items (e.g., favorite book, mug, old souvenir, plant, toy). Record a video or write a reflection on how each object reflects your individuality.",
    safetyRules: "არ აჩვენო ნივთები, რომლებიც შეიცავენ სენსიტიურ დოკუმენტებს ან პირად საბანკო მონაცემებს.",
    safetyRules_en: "Do not show items containing sensitive documents or personal banking details.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 5,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 5,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რომელი ნივთის შერჩევა გაგიჭირდა ყველაზე მეტად და რატომ?",
    reflectionQuestion_en: "Which item was hardest to choose and why?",
    personalDevelopmentReason: "მადლიერების გრძნობის გაღვიძება და ნივთებთან კავშირის რეფლექსია.",
    personalDevelopmentReason_en: "Awakening gratitude and reflecting on connection with everyday objects."
  },
  {
    id: "ch-june-5",
    marathonId: "marathon-june",
    challengeNumber: 5,
    title: "შიშების სიმბოლური განადგურება",
    title_en: "Symbolic Fear Destruction",
    description: "დაწერე ფურცელზე ერთი სოციალური კომპლექსი ან შიში, გადაიღე ვიდეოში მისი ახსნა და საზეიმოდ დახიე ფურცელი.",
    description_en: "Write a social insecurity or fear on a piece of paper, explain it in a video, and solemnly rip it to pieces.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ფურცელზე დიდი ასოებით დაწერე შენი შიში (მაგ. 'ხალხის წინაშე ლაპარაკის კომპლექსი'). კამერის წინ მოკლედ ახსენი, თუ როგორ გიშლის ეს ხელს ცხოვრებაში, შემდეგ კი საზეიმოდ, ემოციურად დახიე ეს ფურცელი წვრილ ნაწილებად და გადაყარე.",
    fullInstructions_en: "Write down your fear in large letters on a paper (e.g., 'Fear of speaking in front of people'). Explain briefly in front of the camera how it blocks you in life, then solemnly and emotionally tear this paper into tiny pieces and discard it.",
    safetyRules: "არ გამოიყენო ცეცხლი ან ბასრი საგნები ფურცლის გასანადგურებლად — ფურცლის ხელით დახევა სრულიად უსაფრთხო და ძლიერი სიმბოლური მოქმედებაა.",
    safetyRules_en: "Do not use fire or sharp objects to destroy the paper — tearing the paper by hand is completely safe and a powerful symbolic choice.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 4,
    challengeCost: 25,
    completionReward: 50,
    publicBraveryBonus: 25,
    points: 50,
    acceptanceCost: 25,
    skipCost: 5,
    publicVideoBonus: 25,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "იგრძენი თუ არა რელიეფური შვება ფურცლის დახევის შემდეგ?",
    reflectionQuestion_en: "Did you feel relief after destroying the paper?",
    personalDevelopmentReason: "ფსიქოსომატური განმუხტვა და შიშებთან განშორების სიმბოლიკა.",
    personalDevelopmentReason_en: "Psychosomatic release and symbolic separation from fears."
  },
  {
    id: "ch-june-6",
    marathonId: "marathon-june",
    challengeNumber: 6,
    title: "სამზარეულოს ინსტრუმენტების სიმფონია",
    title_en: "Kitchen Utensil Symphony",
    description: "შექმენი 30-წამიანი შემოქმედებითი რიტმი მხოლოდ სამზარეულოს უსაფრთხო საოჯახო ნივთების გამოყენებით.",
    description_en: "Create a creative 30-second beat using safe household utensils.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "აიღე ხის კოვზი, პლასტმასის ჯამი ან ქვაბი. დაუკარი ორიგინალური, რიტმული და მხიარული 30-წამიანი კომპოზიცია. ეს დაგეხმარება გათავისუფლდე სხვისი შეფასებების შიშისგან და გამოავლინო შენი ბავშვური, playful ხასიათი.",
    fullInstructions_en: "Grab a wooden spoon, plastic bowl, or kitchen pot. Perform an original, rhythmic, and cheerful 30-second composition. This helps break free from fear of others' judgment and unlocks your playful inner child.",
    safetyRules: "არ გამოიყენო მინის ნივთები, დანები ან სხვა მყიფე საგნები, რომლებიც შეიძლება გატყდეს და დაგაზიანოს.",
    safetyRules_en: "Do not use glass items, knives, or other fragile objects that could break or hurt you during play.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 2,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 15,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 15,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "როდის დაკარგე ბოლოს ასე თამაშის სურვილი ყოველდღიურ ცხოვრებაში?",
    reflectionQuestion_en: "When did you last play so freely in your routine?",
    personalDevelopmentReason: "შინაგანი ბავშვის გაღვიძება და მკაცრი თვითკონტროლის შემცირება.",
    personalDevelopmentReason_en: "Unlocking the inner child and easing up perfectionism."
  },
  {
    id: "ch-june-7",
    marathonId: "marathon-june",
    challengeNumber: 7,
    title: "პოზიტიური წერილი მომავალს",
    title_en: "Positive Letter to the Future",
    description: "დაწერე 50-სიტყვიანი გამამხნევებელი წერილი საკუთარ თავს, რომელსაც 1 წლის შემდეგ წაიკითხავ.",
    description_en: "Write a 50-word encouraging letter to your future self to read in one year.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "აიღე ფურცელი ან დაწერე ტექსტური ფაილი. მიმართე შენს თავს დიდი პატივისცემით, აღიარე შენი ახლანდელი ძალისხმევა და უსურვე გაბედულება. გადაიღე წერილის კითხვის პროცესი ან გააზიარე ტექსტი.",
    fullInstructions_en: "Take a piece of paper or open a text document. Address yourself with genuine respect, acknowledge your current courage, and wish yourself more boldness. Share the letter.",
    safetyRules: "ტექსტი უნდა იყოს მხოლოდ მხარდამჭერი, კრიტიკისა და სინანულის გარეშე.",
    safetyRules_en: "The letter must contain only supportive thoughts, with no critique or regrets.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გრძნობდი თუ არა პასუხისმგებლობას მომავალი ვერსიის წინაშე?",
    reflectionQuestion_en: "Did you feel responsible towards your future self?",
    personalDevelopmentReason: "პოზიტიური თვითდაჯერებულობის ფორმირება და გრძელვადიანი თვითხედვის გაუმჯობესება.",
    personalDevelopmentReason_en: "Promoting long-term self-compassion and optimistic vision."
  },
  {
    id: "ch-june-8",
    marathonId: "marathon-june",
    challengeNumber: 8,
    title: "დილის წუთიერი ცეკვა",
    title_en: "Morning Minute Dance",
    description: "ჩართე საყვარელი მხიარული მელოდია და იცეკვე გიჟურად 1 წუთის განმავლობაში შეფასებების გარეშე.",
    description_en: "Turn on a joyful rhythm and dance foolishly/crazy for 1 minute without self-criticism.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "დილით ან დღის მანძილზე ჩართე რიტმული მუსიკა. დაიწყე უცნაური, ექსპრესიული მოძრაობები. არ იფიქრო იმაზე, ვინმე გიყურებს თუ არა, უბრალოდ გაათავისუფლე სხეული და ჩაწერე ვიდეო.",
    fullInstructions_en: "Tune into a high-tempo track. Express yourself with awkward and strange physical shapes. Do not care how you look, free your body and record.",
    safetyRules: "იცეკვეთ უსაფრთხო ზედაპირზე და მოერიდეთ ბასრ ავეჯს.",
    safetyRules_en: "Make sure you dance on safe floors and avoid sharp furniture corners.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 15,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 15,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "როგორ შეიცვალა შენი ფიზიკური ენერგია ცეკვის შემდეგ?",
    reflectionQuestion_en: "How did your bodily energy level feel after that minute?",
    personalDevelopmentReason: "სხეულებრივი ბლოკების მოხსნა და ენდორფინების დონის მომატება.",
    personalDevelopmentReason_en: "Releasing somatic blockages and raising natural endorphins."
  },
  {
    id: "ch-june-9",
    marathonId: "marathon-june",
    challengeNumber: 9,
    title: "ბოჰემური ყავა ჩემს თავს",
    title_en: "Bohemian Coffee for Myself",
    description: "მოამზადე ყავა/ჩაი განსაუთრებული მოუთმენლობითა და ელეგანტური საზეიმო მირთმევით.",
    description_en: "Prepare coffee/tea with special artistic care and drink it with royal elegance.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ჩვეულებრივი ყავის სმა აქციე ხელოვნებად: გამოიყენე საუკეთესო ჭიქა, მორთე დარიჩინით ან ლიმონით, დაჯექი ლამაზ პოზაში და დატკბი ყოველი ყლუპით. გადაიღე და გაგვიზიარე.",
    fullInstructions_en: "Turn drinking coffee into a sensory art: use your classy cup, add spices, take an elegant posture, and enjoy every sip. Capture this ceremony.",
    safetyRules: "მოერიდე ცხელი სასმლის დაქცევას ან დამწვრობას.",
    safetyRules_en: "Take extreme precautions to avoid spilling or scalding yourself with hot water.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "photo" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რატომ ვზოგავთ ხშირად საუკეთესო ნივთებს მხოლოდ განსაკუთრებული სტუმრებისთვის?",
    reflectionQuestion_en: "Why do we avoid using our best cups/plates except when guests are over?",
    personalDevelopmentReason: "თვითღირებულების შეგრძნების გაძლიერება ყოველდღიურ წვრილმანებში.",
    personalDevelopmentReason_en: "Elevating personal value in mundane moments of the routine."
  },
  {
    id: "ch-june-10",
    marathonId: "marathon-june",
    challengeNumber: 10,
    title: "15-წუთიანი მობილურის გარეშე გასეირნება",
    title_en: "15-Minute No-Phone Walk",
    description: "გადი გარეთ ზუსტად 15 წუთით მობილური ტელეფონის გარეშე და დააკვირდი 3 უჩვეულო დეტალს.",
    description_en: "Walk outside for 15 minutes completely without your phone, and observe 3 unusual details.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "დატოვე სმარტფონი სახლში. გადი გარეთ, ისუნთქე, დააკვირდი გარემოს, ხეებს, ადამიანთა მზერას. სახლში დაბრუნების შემდეგ დაწერე 3 დეტალი, რომელიც აქამდე არ შეგიმჩნევია შენს უბანში.",
    fullInstructions_en: "Leave your smartphone on your desk. Step outside, breathe, watch people's eyes, look around. Report three brand new physical details you never noticed before.",
    safetyRules: "გაისეირნეთ უსაფრთხო, ნაცნობ მარშრუტზე.",
    safetyRules_en: "Walk on a safe, familiar neighborhood trail.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 2,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 10,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გქონდათ სმარტფონის არქონის გამო შფოთვა გასეირნების დასაწყისში?",
    reflectionQuestion_en: "Did you feel phantom phone notification anxiety initially?",
    personalDevelopmentReason: "ციფრული დეტოქსი და აწმყოს აღქმა (mindfulness).",
    personalDevelopmentReason_en: "Promoting digital detox and high immersion in the present moment."
  },

  // ================= JULY CHALLENGES (10) =================
  {
    id: "ch-july-1",
    marathonId: "marathon-july",
    challengeNumber: 1,
    title: "ახალი ადამიანის გაღიმება",
    title_en: "Smiling at a Stranger",
    description: "გაიღიმე გულწრფელად და თბილად ქუჩაში სრულიად უცხო ადამიანის მიმართ და გაგვიზიარე განცდა.",
    description_en: "Smile sincerely and warmly at a total stranger on the street and share the feeling.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ქუჩაში ყოფნისას შეარჩიე უსაფრთხო, სასიამოვნო გამომეტყველების მქონე გამვლელი, გაუსწორე თვალი და უბრალოდ გაუღიმე. ჩაწერე მოკლე ხმოვანი/ვიდეო რეფლექსია, როგორ უპასუხა მან შენს ღიმილს.",
    fullInstructions_en: "When outside, spot a friendly passerby, make eye contact, and offer a soft, polite smile. Note down or share how they responded.",
    safetyRules: "გააკეთეთ ეს უსაფრთხოდ, არ შეაწუხოთ ან შეაშინოთ ადამიანები.",
    safetyRules_en: "Perform this in a light, completely safe manner without bothering anyone.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 2,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რამდენად ადვილი აღმოჩნდა უცხო ადამიანისთვის თვალის გასწორება?",
    reflectionQuestion_en: "How easy was it to hold eye contact with a stranger?",
    personalDevelopmentReason: "სოციალური უნდობლობისა და უცხოობის პირველი ბარიერის მსხვრევა.",
    personalDevelopmentReason_en: "Breaking social isolation and initial barriers of mistrust."
  },
  {
    id: "ch-july-2",
    marathonId: "marathon-july",
    challengeNumber: 2,
    title: "რეკომენდაციის წერილი უცნობს",
    title_en: "Recommendation Note to a Stranger",
    description: "დატოვე პატარა დადებითი სტიკერი ან წერილი საჯარო ადგილას, რათა სხვა ადამიანმა იპოვოს და გაიხაროს.",
    description_en: "Leave a tiny positive sticker or note in a public area for someone else to find and smile.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "პატარა ფურცელზე დაწერე თბილი სიტყვა, მაგალითად: 'შენ განსაკუთრებული ხარ!', 'ეს დღე წარმატებული იქნება!'. დატოვე ის კაფეს მაგიდაზე, წიგნში ან გაჩერებაზე. გადაუღე ფოტო.",
    fullInstructions_en: "Write a warm sentence like 'You are unique!' or 'Have an amazing day!' on a post-it note. Stick it in a bookstore, bus stop, or cafe table.",
    safetyRules: "არ დააბინძუროთ გარემო და არ დატოვოთ პერსონალური საკონტაქტო მონაცემები.",
    safetyRules_en: "Do not litter or share personal credentials/phone numbers.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 5,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 5,
    submissionType: "photo" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გიყვარს თუ არა მოულოდნელი საჩუქრების მიღება?",
    reflectionQuestion_en: "Do you personally like receiving random positive signs?",
    personalDevelopmentReason: "ალტრუისტული ჟესტის განხორციელება და პოზიტივის გავრცელება.",
    personalDevelopmentReason_en: "Performing altruistic acts to distribute positive mental energy."
  },
  {
    id: "ch-july-3",
    marathonId: "marathon-july",
    challengeNumber: 3,
    title: "უჩვეულო კომპლიმენტი",
    title_en: "Unusual Compliment",
    description: "უთხარი მეგობარს ან ოჯახის წევრს მისი ხასიათის თვისებაზე ისეთი კომპლიმენტი, რომელიც აქამდე არ გითქვამს.",
    description_en: "Tell a close friend/family member an honest compliment about their personality you've never mentioned.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "მიაქციე ყურადღება მის უნიკალურ უნარს (მაგ: 'აღფრთოვანებული ვარ შენი მოსმენის ნიჭით'). უთხარი ეს გულწრფელად და გაგვიზიარე მისი რეაქცია.",
    fullInstructions_en: "Focus on a deep asset (e.g. 'I truly admire your deep listening skills'). Express it honestly and capture the emotional return.",
    safetyRules: "კომპლიმენტი უნდა იყოს რეალური, ყოველგვარი ირონიისა და სიყალბის გარეშე.",
    safetyRules_en: "The compliment must be authentic and void of ironies or fabrications.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გაგიადვილდა თუ არა სათქმელის პოვნა?",
    reflectionQuestion_en: "Was it simple to find the right words?",
    personalDevelopmentReason: "ემპათიის განვითარება და კომუნიკაციის ხარისხის ამაღლება.",
    personalDevelopmentReason_en: "Deepening empathy and improving communication richness."
  },
  {
    id: "ch-july-4",
    marathonId: "marathon-july",
    challengeNumber: 4,
    title: "ჩემი არასრულყოფილების სიყვარული",
    title_en: "Loving My Imperfection",
    description: "აღიარე შენი ერთი წვრილმანი შეცდომა ან ნაკლი და გვითხარი, რატომ არის ის შენი უნიკალურობის ნაწილი.",
    description_en: "Accept one minor self-perceived flaw and explain why it is actually a beautiful part of your identity.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ჩაწერე ვიდეო, სადაც ამბობ: 'კი, მე ზოგჯერ ზედმეტად ვჩქარობ, მაგრამ ეს ჩემი ენერგიულობის ნიშანია'. ისწავლე თვითშეფასების დაცვა.",
    fullInstructions_en: "Record a video stating a perceived quirk (e.g., 'Yes, I sometimes talk too fast, but it is just my high-energy spark'). Teach your mind self-acceptance.",
    safetyRules: "არ მიაყენოთ საკუთარ თავს შეურაცხყოფა, საუბარი უნდა იყოს მეგობრული.",
    safetyRules_en: "The tone must be fully supportive, avoiding self-bullying.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 15,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 15,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "საკუთარ თავზე საუბარი უფრო მარტივია თუ სხვების შექება?",
    reflectionQuestion_en: "Is it harder to compliment yourself or others?",
    personalDevelopmentReason: "პერფექციონიზმთან გამკლავება და თვითმიმღებლობა.",
    personalDevelopmentReason_en: "Combating perfectionism and enhancing self-embrace."
  },
  {
    id: "ch-july-5",
    marathonId: "marathon-july",
    challengeNumber: 5,
    title: "ტაშის ხმა სიჩუმეში",
    title_en: "Clapping in Silence",
    description: "საკუთარ ოთახში მარტო ყოფნისას, ხმამაღლა, ენერგიულად დაუკარი ტაში შენს თავს 15 წამის განმავლობაში.",
    description_en: "When alone in your room, clap loudly and energetically for yourself for 15 seconds.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "დადექი ოთახის ცენტრში, ჩართე კამერა და მთელი ემოციით, ამაყად დაუკარი ტაში შენს თავს — თითქოს მსოფლიო სცენაზე დგახარ.",
    fullInstructions_en: "Stand in the middle of your room, turn on the video, and proudly clap for yourself as if you just finished a legendary performance.",
    safetyRules: "არ არის საჭირო ხელების დაზიანება — უბრალოდ იგრძენი პოზიტიური აუდიტორიის განცდა.",
    safetyRules_en: "There is no need to make hands sore — just channel physical affirmation.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 2,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რა შეგრძნება იყო საკუთარი თავის მხარდაჭერა?",
    reflectionQuestion_en: "How did manual self-applause feel?",
    personalDevelopmentReason: "თვითშეფასების დამოუკიდებელი წყაროს განვითარება.",
    personalDevelopmentReason_en: "Cultivating an autonomous source of self-approvals."
  },
  {
    id: "ch-july-6",
    marathonId: "marathon-july",
    challengeNumber: 6,
    title: "ხმამაღალი შეკითხვა ბიბლიოთეკაში",
    title_en: "Loud Request in the Library",
    description: "გამოავლინე გამბედაობა რომელიმე მშვიდ საჯარო სივრცეში და სთხოვე კონსულტანტს დახმარება მკაფიო ხმით.",
    description_en: "Show courage in a quiet store/library by asking a clean, clear question to an assistant.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "მიდი მაღაზიაში ან ბიბლიოთეკაში. მშვიდად, მაგრამ მკაფიოდ და თავდაჯერებულად ჰკითხე კონსულტანტს რამე წიგნზე ან ნივთზე. ჩაწერე გამოცდილება რეფლექსიაში.",
    fullInstructions_en: "Visit a quiet store or bookstore. Ask the support assistant a specific query clearly and without whispering. Share the takeaways.",
    safetyRules: "იყავით თავაზიანი და პატივისცემით განწყობილი, არ შექმნათ კონფლიქტი.",
    safetyRules_en: "Stay fully polite, safe, and positive without making a scene.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 10,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "იცვლება თუ არა შენი ხმის ტემბრი დაძაბულობისას?",
    reflectionQuestion_en: "Does your voice alter during public social interactions?",
    personalDevelopmentReason: "ხმის თავისუფლად გამოყენება და შიშის დაძლევა.",
    personalDevelopmentReason_en: "Vocal power practice and conquering communication fears."
  },
  {
    id: "ch-july-7",
    marathonId: "marathon-july",
    challengeNumber: 7,
    title: "ბავშვური ჟესტი ქუჩაში",
    title_en: "Playful Gesture on the Street",
    description: "გაიარე ქუჩაში კლასობანას სტილით 3 ნაბიჯი (ხტუნვით) და იგრძენი ბავშვური თავისუფლება.",
    description_en: "Hop/skip 3 steps on a pavement sidewalk like a happy child and feel inner lightness.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "როცა გარეთ ხარ, დაინახე ასფალტის დახაზული მონაკვეთი და უცებ, მხიარულად გადახტი 3-ჯერ, თითქოს ბავშვობაში ხარ. გადაიღე ეს წამიერი გამარჯვება.",
    fullInstructions_en: "When outside, jump/hop nicely 3 times on physical squares on the tiles. Accept that people might look, and capture the scene.",
    safetyRules: "მოერიდეთ მანქანების გზას ან მოლიპულ ზედაპირებს.",
    safetyRules_en: "Avoid traffic sections or wet tiles to prevent physical damage.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 4,
    challengeCost: 20,
    completionReward: 40,
    publicBraveryBonus: 20,
    points: 40,
    acceptanceCost: 20,
    skipCost: 5,
    publicVideoBonus: 20,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რამდენად გაინტერესებდა გარშემომყოფების რეაქცია?",
    reflectionQuestion_en: "To what extent did you look for strangers' judgment?",
    personalDevelopmentReason: "სოციალური სირცხვილის შიშის კოგნიტური დესენსიბილიზაცია.",
    personalDevelopmentReason_en: "Cognitive desensitization against social shame indicators."
  },
  {
    id: "ch-july-8",
    marathonId: "marathon-july",
    challengeNumber: 8,
    title: "ჩანთის გამოცანა",
    title_en: "The Handbag Riddle",
    description: "აჩვენე შენი ჩანთის ან ჯიბის 3 ყველაზე საჭირო შიგთავსი და ახსენი მათი მნიშვნელობა.",
    description_en: "Show 3 useful items inside your bag/pocket and write an elegant history of them.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ამოალაგე ნივთები, განათავსე მაგიდაზე. გადაიღე ფოტო ან ჩაწერე ვიდეო, სადაც გვიყვები, რატომ ატარებ მათ ყოველდღიურად.",
    fullInstructions_en: "Unpack items, place them neatly on a flat surface. Record why they accompany you.",
    safetyRules: "არ გაასაჯაროოთ დოკუმენტები, გასაღებები ან ფინანსური მონაცემები.",
    safetyRules_en: "Don't showcase ID papers, room keys or payment plastic.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 5,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 5,
    submissionType: "photo" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "ყველა ნივთი ნამდვილად გამოსადეგია?",
    reflectionQuestion_en: "Are all three items practically vital?",
    personalDevelopmentReason: "შინაგანი კომფორტის რეფლექსია ჩვენს გარშემო არსებული ატრიბუტებით.",
    personalDevelopmentReason_en: "Exploring personal attributes and self-organization indicators."
  },
  {
    id: "ch-july-9",
    marathonId: "marathon-july",
    challengeNumber: 9,
    title: "პატიების რიტუალი",
    title_en: "Ritual of Forgiveness",
    description: "საკუთარ თავს აპატიე ერთი ძველი, წარსული შეცდომა და დაწერე ეს გულახდილი ჩანაწერი.",
    description_en: "Forgive yourself for one old regret and document it in a private/public journal entry.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "დაწერე ფრაზა: 'მე ვპატიობ ჩემს თავს იმ შეცდომას... ეს იყო გაკვეთილი. ახლა მე თავისუფალი ვარ'. გააზიარე ეს თამამი აქტი.",
    fullInstructions_en: "Write: 'I fully forgive myself for ... it was a tough lesson. I am free to move on now'. Send the reflection report.",
    safetyRules: "არ ჩაუღრმავდეთ მატრავმირებელ გამოცდილებებს დახმარების გარეშე, აირჩიეთ მსუბუქი სინანული.",
    safetyRules_en: "Do not touch deeply traumatic topics, go with soft social or minor errors.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 2,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "იგრძენი თუ არა მხრების სიმსუბუქე ამ ტექსტის წერისას?",
    reflectionQuestion_en: "Did you feel an immediate lifting off of anxiety?",
    personalDevelopmentReason: "თვითდანაშაულების გრძნობის შემცირება და თავდაჯერება.",
    personalDevelopmentReason_en: "Lowering self-blaming indices and restoring confidence."
  },
  {
    id: "ch-july-10",
    marathonId: "marathon-july",
    challengeNumber: 10,
    title: "ნიღბის მოხსნა",
    title_en: "Unveiling the Mask",
    description: "მოიხსენი ყოველდღიური სოციალური როლი 5 წუთით და უბრალოდ იყავი მშვიდად.",
    description_en: "Step out of your daily social persona/role for 5 minutes and just rest in pure presence.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "დაჯექი კომფორტულად, დახუჭე თვალები, არ იფიქრო შენს პროფესიაზე, მოვალეობებზე ან იმაზე, როგორ უნდა გამოიყურებოდე. დაწერე ამის შესახებ.",
    fullInstructions_en: "Sit in silence for 5 minutes. Dismiss your titles, targets, and expected postures. Connect to your raw self and share.",
    safetyRules: "გამოწვევა სრულდება მშვიდ, უსაფრთხო გარემოში.",
    safetyRules_en: "Perform in a quiet, hazard-free setting.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 1,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 10,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გახასიათებთ თუ არა როლების გადამეტებული მორგება?",
    reflectionQuestion_en: "Do you over-identify with social masks?",
    personalDevelopmentReason: "ეგოცენტრული დამცავი ბარიერების შემცირება.",
    personalDevelopmentReason_en: "Mitigating protective ego barriers and self-consciousness."
  },

  // ================= AUGUST CHALLENGES (10) =================
  {
    id: "ch-aug-1",
    marathonId: "marathon-august",
    challengeNumber: 1,
    title: "მოულოდნელი საჩუქარი",
    title_en: "The Random Act of Kindness",
    description: "შეუძინე უცნობ ქუჩის მუსიკოსს ან გამყიდველს ცივი წყალი/ნაყინი ზაფხულის სიცხეში.",
    description_en: "Buy a cold drink or ice cream for a street musician or hard-working kiosk seller.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ზაფხულის სიცხეში შეამჩნიე ადამიანი, რომელიც გარეთ შრომობს. აჩუქე მას ცივი მინერალური წყალი ან ნაყინი, უთხარი: 'გმადლობთ შრომისთვის!'. გაგვიზიარე განცდები.",
    fullInstructions_en: "Spot someone working hard in the August heat. Hand them a cold beverage with a polite word. Report.",
    safetyRules: "იყავით სრულიად თავაზიანი და ნუ დაჟინებით შესთავაზებთ, თუ ადამიანს უხერხულობა აქვს.",
    safetyRules_en: "Do not push if the person seems highly reluctant or uncomfortable.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 15,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 15,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რა იგრძენი გაცემის ჟესტის დასრულებისას?",
    reflectionQuestion_en: "What shifted in your chest after making the gesture?",
    personalDevelopmentReason: "ალტრუიზმის და სოციალური შეგრძნების ინტეგრაცია.",
    personalDevelopmentReason_en: "Fostering organic integration with the social environment."
  },
  {
    id: "ch-aug-2",
    marathonId: "marathon-august",
    challengeNumber: 2,
    title: "ხეზე ჩახუტება პარკში",
    title_en: "Hugging a Tree",
    description: "მიდი პარკში და ჩაეხუტე შენს საყვარელ ხეს 10 წამის განმავლობაში, ბუნებასთან დასაკავშირებლად.",
    description_en: "Hug a beautiful tree in a public park for 10 seconds to align with nature.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "მიდი ახლომდებარე პარკში. აარჩიე დიდი, ლამაზი ხე, მიდი მასთან და გულწრფელად ჩაეხუტე. ნუ ინერვიულებ სხვების მზერაზე, დახუჭე თვალები. გადაიღე პროცესი.",
    fullInstructions_en: "Visit a park. Choose a tree, approach, and warmly hug its trunk for 10 seconds. Disregard onlookers' gazes and capture it.",
    safetyRules: "დარწმუნდით, რომ ხეზე არ არის მწერები ან რამე სახიფათო საფარი.",
    safetyRules_en: "Check the bark for insects or sharp edges before physical contact.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 20,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 20,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "იგრძენით თავი უცნაურად ამ მოქმედებისას?",
    reflectionQuestion_en: "Did you experience a feeling of weirdness while hugging it?",
    personalDevelopmentReason: "კავშირი სამყაროსთან და გარე აზრისგან გათავისუფლება.",
    personalDevelopmentReason_en: "Deepening connectivity with nature and letting go of public opinions."
  },
  {
    id: "ch-aug-3",
    marathonId: "marathon-august",
    challengeNumber: 3,
    title: "უცხო ენაზე მისალმება",
    title_en: "Greeting in an Unknown Tongue",
    description: "მიესალმე მაღაზიის კონსულტანტს ან მეზობელს უჩვეულო, უცხო ენაზე (მაგ. 'კონიჩივა' ან 'ბონჟურ').",
    description_en: "Greet a cashier/neighbor in a fun foreign language with a smiling grin (e.g. 'Bonjour' or 'Konnichiwa').",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "თავდაჯერებული ნაბიჯით მიდი მაღაზიაში. ღიმილით მიესალმე 'Bonjour!' და შემდეგ ჩვეულებრივ გააგრძელე საუბარი ქართულად. გააზიარე რეფლექსია.",
    fullInstructions_en: "Enter a kiosk or bakery. Greet them with a big smile and a polite 'Bonjour!'. Proceed with your Georgian request smoothly. Describe the interaction.",
    safetyRules: "გამოიყენეთ მხოლოდ პოზიტიური და კეთილგანწყობილი მისალმება. არ გახადოთ ეს დამცინავი.",
    safetyRules_en: "Ensure high positive context. Avoid sarcasm or confusing gestures.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 2,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "როგორ იმოქმედა თქვენს მღელვარებაზე ასეთმა მოულოდნელმა დასაწყისმა?",
    reflectionQuestion_en: "How did starting with a foreign word impact your tension level?",
    personalDevelopmentReason: "სტერეოტიპული ქცევის მოდელის დარღვევა და კომუნიკაციური მოქნილობა.",
    personalDevelopmentReason_en: "Breaking repetitive behavior loops and building verbal agility."
  },
  {
    id: "ch-aug-4",
    marathonId: "marathon-august",
    challengeNumber: 4,
    title: "პოეზიის ხმამაღალი კითხვა",
    title_en: "Reading Poetry Aloud",
    description: "წაიკითხე შენი საყვარელი ლექსის 1 კუპლეტი ხმამაღლა, გამომსახველობითად კამერის წინ.",
    description_en: "Read 1 stanza of your favorite poem of choice aloud and expressively for our player community.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "შეარჩიე ლექსი. ჩართე კამერა, დადექი სწორად და წაიკითხე ის მთელი გრძნობით. ეს გეხმარება საჯაროდ ლაპარაკის კომპლექსის მოხსნაში.",
    fullInstructions_en: "Pick a beautiful lyric stanza. Put the camera on, stand straight, and deliver it with depth. Helps with public performance stage fright.",
    safetyRules: "აირჩიეთ პოზიტიური, შთამაგონებელი შინაარსის ლექსი.",
    safetyRules_en: "Pick positive, inspiring verses.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 2,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 15,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 15,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გიყვარდა თუ არა ბავშვობაში ლექსების თქმა სტუმრების წინაშე?",
    reflectionQuestion_en: "Did you use to enjoy reciting poems for guests when you were a kid?",
    personalDevelopmentReason: "ორატორული გამბედაობა და ემოციური ექსპრესია.",
    personalDevelopmentReason_en: "Developing oratorical bravery and emotional expressiveness."
  },
  {
    id: "ch-aug-5",
    marathonId: "marathon-august",
    challengeNumber: 5,
    title: "ჩემი შიშების მუზეუმი",
    title_en: "Museum of My Insecurities",
    description: "დახატე ან გამოსახე ფურცელზე შენი 3 კომპლექსი, როგორც 'მუზეუმის ექსპონატი' და გაგვიზიარე მისი ფოტო.",
    description_en: "Draw or map 3 of your insecurities as 'museum items' and share the result.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "აიღე მარკერები. დახატე შიშები მხიარული ან უცნაური ფორმით, დააწერე სახალისო სახელები (მაგ: 'უხერხული წითლობის ექსპონატი'). ასე ჩვენ ვამცირებთ მათ ზომას.",
    fullInstructions_en: "Take paint or pencils. Represent fears as cataloged items in a humorous, mini gallery (e.g., 'The Crimson Blush Sculpture'). Taming them down.",
    safetyRules: "ეს არის მხიარული თამაში, ნუ გახდით მას მძიმეს.",
    safetyRules_en: "This is a fun exercise, keep it light and cartoonish.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 10,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "photo" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გრძნობთ თუ არა კონტროლს შიშებზე, როცა მათ ქაღალდზე გამოსახავთ?",
    reflectionQuestion_en: "Do you gain a sense of control when externalizing fears on paper?",
    personalDevelopmentReason: "ექსტერნალიზაციის ტექნიკა შიშების დეტრავმატიზაციისთვის.",
    personalDevelopmentReason_en: "Applying externalization methodologies to neutralize insecurities."
  },
  {
    id: "ch-aug-6",
    marathonId: "marathon-august",
    challengeNumber: 6,
    title: "მადლიერების ყულაბა",
    title_en: "The Gratitude Piggybank",
    description: "დაწერე 3 მადლიერი აზრი იმ ადამიანებზე, რომლებმაც შენს ცხოვრებაში ბილიკი გაკაფეს.",
    description_en: "Write 3 grateful facts about people who cleared paths or supported your life.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ამოარჩიე 3 პიროვნება (მასწავლებელი, მეგობარი, ავტორი). დაწერე მოკლედ, რა ისწავლე მათგან და როგორ შეცვალეს შენი მსოფლმხედველობა.",
    fullInstructions_en: "Recall three special individuals (e.g. mentor, buddy, author). Write what you acquired from them and why it modified your horizon.",
    safetyRules: "გამოიყენეთ მხოლოდ პოზიტიური, მადლიერი ემოციები.",
    safetyRules_en: "Maintain exclusively warm, grateful feelings.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 5,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 5,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გაქვს თუ არა მათთან კავშირი ახლა?",
    reflectionQuestion_en: "Are you still in touch with them today?",
    personalDevelopmentReason: "პოზიტიური ფსიქოლოგიური მდგრადობის ამაღლება.",
    personalDevelopmentReason_en: "Enhancing psychological resilience indices."
  },
  {
    id: "ch-aug-7",
    marathonId: "marathon-august",
    challengeNumber: 7,
    title: "10 წუთი შეფასების გარეშე",
    title_en: "10 Minutes Without Criticism",
    description: "გაატარე ზუსტად 10 წუთი ყოველგვარი კრიტიკული აზრის გაჟღერების გარეშე როგორც საკუთარი თავის, ისე სხვების მიმართ.",
    description_en: "Spend exactly 10 minutes without making a single critical or negative remark about yourself or anyone.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "დააყენე ტაიმერი. 10 წუთის მანძილზე აკონტროლე ფიქრები: მხოლოდ დადებითი, მიმღებლური რეალობა. ჩაწერე შენი დაკვირვება სოციალურ რეფლექსიაში.",
    fullInstructions_en: "Set a timer for 10 minutes. Watch your stream of thoughts: maintain absolute cognitive acceptance. Note how often negative filters try to pop in.",
    safetyRules: "ეს არის მენტალური ვარჯიში, იყავით მოთმინებით აღჭურვილი საკუთარ თავთან.",
    safetyRules_en: "This is a pure cognitive trial, be loving and patient with yourself.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 2,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 10,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რამდენად ხშირად ჩნდება ნეგატიური აზრები არაცნობიერად?",
    reflectionQuestion_en: "How frequent were spontaneous auto-critical thoughts?",
    personalDevelopmentReason: "ნეგატიური აზროვნების ფილტრების გაცნობიერება.",
    personalDevelopmentReason_en: "Identifying auto-pilot negative filters in the cognitive stream."
  },
  {
    id: "ch-aug-8",
    marathonId: "marathon-august",
    challengeNumber: 8,
    title: "უჩვეულო ფეხსაცმელი",
    title_en: "The Quirky Shoes Walk",
    description: "გადი ეზოში ან ქუჩაში განსხვავებული ფეხსაცმლით (მაგ: მარცხენა თეთრი, მარჯვენა შავი) და იგრძენი შინაგანი უშიშრობა.",
    description_en: "Walk outside wearing mismatched socks or shoes (e.g., left white, right black) and command inner boldness.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ჩაიცვი განსხვავებული წყვილები. გაიარე მცირე მანძილი ეზოში ან სადარბაზოში, შეამჩნიე შენი განცდა, როცა არ მისდევ სტანდარტებს. ჩაწერე ვიდეო.",
    fullInstructions_en: "Wear two different shoes or distinct cozy socks outside. Take a short walk near your house or building. Capture your steps on video.",
    safetyRules: "გამოიყენეთ კომფორტული და უსაფრთხო ფეხსაცმელი, რათა არ წაიქცეთ.",
    safetyRules_en: "Use flat, secure sneakers so there is no hazard of twisting ankles.",
    difficulty: "hard" as const,
    emotionalCourageLevel: 4,
    challengeCost: 25,
    completionReward: 50,
    publicBraveryBonus: 25,
    points: 50,
    acceptanceCost: 25,
    skipCost: 5,
    publicVideoBonus: 25,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "შეამჩნიეს თუ არა ეს გამვლელებმა?",
    reflectionQuestion_en: "Did any passerby actually pay attention?",
    personalDevelopmentReason: "კოგნიტური მოქნილობის გაზრდა არაკონფორმიზმის პრაქტიკით.",
    personalDevelopmentReason_en: "Upgrading non-conformity tolerance to reduce situational anxiety."
  },
  {
    id: "ch-aug-9",
    marathonId: "marathon-august",
    challengeNumber: 9,
    title: "განსხვავებული მარშრუტი",
    title_en: "Taking the Unfamiliar Trail",
    description: "დაბრუნდი სამსახურიდან / მაღაზიიდან სრულიად განსხვავებული, გრძელი და ლამაზი გზით, რათა იგრძნო თავგადასავალი.",
    description_en: "Return home via an entirely unaccustomed, longer, scenic path to inspire discovery.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "აუხვიე უცნობ ჩიხში, აღმოაჩინე ახალი შენობები, ეზოები და საყოფაცხოვრებო პალიტრა. გადაუღე ფოტო 1 ლამაზ ობიექტს.",
    fullInstructions_en: "Turn into an unfamiliar alleyway. Discover new structures, tiny gardens, or local art. Capture one beautiful object.",
    safetyRules: "გამოიყენეთ მხოლოდ განათებული, უსაფრთხო ქალაქის მარშრუტები.",
    safetyRules_en: "Only utilize safe, well-lit urban environments.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 5,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 5,
    submissionType: "photo" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "აღმოაჩინე რამე საინტერესო ლოკაცია?",
    reflectionQuestion_en: "Did you uncover any pretty spatial corners?",
    personalDevelopmentReason: "ნეიროპლასტიურობის ხელშეწყობა გარემო ცვლილებით.",
    personalDevelopmentReason_en: "Promoting structural neuroplasticity through spatial changes."
  },
  {
    id: "ch-aug-10",
    marathonId: "marathon-august",
    challengeNumber: 10,
    title: "ჩემი შინაგანი პოეტი",
    title_en: "My Inner Poet",
    description: "დაწერე 4-ხაზიანი მხიარული რითმა 'ბიფურკაციის' შესახებ და გაგვიზიარე ის.",
    description_en: "Draft a lighthearted 4-line rhyme about the concept of 'Bifurcation' and share it.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "იყავი შემოქმედებითი. დაწერე მარტივი, თუნდაც სასაცილო ლექსი იმაზე, როგორ უმკლავდები შიშებს და როგორ იღებ ბონუს ქულებს. გამოაქვეყნე ტექსტის სახით.",
    fullInstructions_en: "Unleash creativity. Construct a mini rhyme on overcoming constraints and receiving reward scores. Submit printed text.",
    safetyRules: "დაიცავით ეთიკის ნორმები და პოზიტიური განწყობა.",
    safetyRules_en: "Observe positive social ethics and supportive phrasing.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გრძნობდი თუ არა თავს ინსპირირებულად წერისას?",
    reflectionQuestion_en: "Did writing awaken an artistic drive?",
    personalDevelopmentReason: "აზრების შემოქმედებითი სუბლიმაცია და იუმორი.",
    personalDevelopmentReason_en: "Creative sublimation of cognitive blocks through verbal humors."
  },

  // ================= SEPTEMBER CHALLENGES (10) =================
  {
    id: "ch-sept-1",
    marathonId: "marathon-september",
    challengeNumber: 1,
    title: "შოპინგი კალათის გარეშე",
    title_en: "Shopping Without a Basket",
    description: "შედი სუპერმარკეტში და იყიდე 3 ნივთი ისე, რომ არ აიღო კალათა — დაიჭირე ხელში და გადაიხადე.",
    description_en: "Enter a grocery store and buy 3 small items holding them strictly in your hands without a basket.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "აიღე 3 წვრილმანი ნივთი (მაგ: წვენი, შოკოლადი, ხილი). მიიტანე სალარომდე ხელში ბალანსირებით, მიესალმე მხიარულად და გადაიხადე. დაწერე ამის შესახებ.",
    fullInstructions_en: "Pick up 3 separate objects. Carry them nicely balanced to the service till, thank the employee, and check out. Document the task.",
    safetyRules: "ნუ აიღებთ მძიმე ან მსხვრევად ნივთებს, რომლებიც შეიძლება დაგივარდეთ.",
    safetyRules_en: "Avoid picking fragile goods or heavy boxes to prevent messy spills.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 5,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 5,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გრძნობდით უხერხულობას იმის შიშით, რომ ვინმეს ქურდი არ ეგონეთ?",
    reflectionQuestion_en: "Did you feel minor panic that security might suspect shoplifting?",
    personalDevelopmentReason: "ფსიქოლოგიური რეზისტენტობის ამაღლება სოციალური მზერის ქვეშ.",
    personalDevelopmentReason_en: "Building mental resilience under passing social monitoring scenarios."
  },
  {
    id: "ch-sept-2",
    marathonId: "marathon-september",
    challengeNumber: 2,
    title: "გულახდილი სატელეფონო საუბარი",
    title_en: "The Deep Call Conversation",
    description: "დაურეკე ძველ ნაცნობს ან ახლობელს და უთხარი, რაოდენ ძვირფასია ის შენთვის.",
    description_en: "Call an old acquaintance or distant partner and convey how much their presence meant to you.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "განახორციელე 3-წუთიანი ზარი. უთხარი: 'გამარჯობა, უბრალოდ გამახსენდი და მინდოდა მეთქვა, რომ მიფასებხარ'. ჩაწერე შენი ემოციები საუბრის შემდეგ.",
    fullInstructions_en: "Place a quick voice call. State: 'Hey, I was just reflecting on our memories and wanted to let you know I rate our values'. Record your mood.",
    safetyRules: "არ გამოიყენოთ საუბარი ძველი კონფლიქტების გასარჩევად, მხოლოდ პოზიტივი.",
    safetyRules_en: "Strictly avoid digging old conflicts; stay explicitly warm.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 10,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რამდენ ხანს აჭიანურებდი ამ ზარის განხორციელებას?",
    reflectionQuestion_en: "For how long have you been putting off this interaction?",
    personalDevelopmentReason: "სოციალური კავშირების აღდგენა და ემოციური გახსნილობა.",
    personalDevelopmentReason_en: "Rebuilding social networks and building emotional vulnerability."
  },
  {
    id: "ch-sept-3",
    marathonId: "marathon-september",
    challengeNumber: 3,
    title: "საკუთარი თავის ინტერვიუ",
    title_en: "Self-Interview Recording",
    description: "დაუსვი საკუთარ თავს 1 რთული კითხვა ცხოვრებაზე, ჩაწერე ვიდეო პასუხი და შეაფასე შენი გამბედაობა.",
    description_en: "Ask yourself 1 serious question on video, answer it, and grade your situational confidence.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "მიმართე კამერა შენსკენ. ჰკითხე: 'რისი გაკეთება გინდა ყველაზე მეტად ცხოვრებაში, მაგრამ გეშინია?'. უპასუხე გულახდილად, ემოციურად.",
    fullInstructions_en: "Face the camera. Inquire: 'What is the number one thing you crave to achieve but fear?' Deliver your answers with pride and raw voice.",
    safetyRules: "იყავით გულწრფელი, მაგრამ ნუ გადახვალთ თვითდადანაშაულებაში.",
    safetyRules_en: "Remain transparent, but skip any self-flagellatings.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 4,
    challengeCost: 20,
    completionReward: 40,
    publicBraveryBonus: 20,
    points: 40,
    acceptanceCost: 20,
    skipCost: 5,
    publicVideoBonus: 20,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "ხმამაღლა თქმამ უფრო ნათელი გახადა შენი მიზნები?",
    reflectionQuestion_en: "Did speaking it aloud clarify your life ambitions?",
    personalDevelopmentReason: "შიდა კონფლიქტების იდენტიფიცირება და ხმოვანი რეალიზება.",
    personalDevelopmentReason_en: "Verbalizing hidden conflicts to lower their cognitive threat levels."
  },
  {
    id: "ch-sept-4",
    marathonId: "marathon-september",
    challengeNumber: 4,
    title: "5-წუთიანი მედიტაცია მეტროში",
    title_en: "5-Minute Transit Reflection",
    description: "მგზავრობისას 5 წუთის განმავლობაში შეინარჩუნე სიმშვიდე, ღრმად ისუნთქე და დააკვირდი აურზაურს შეფასების გარეშე.",
    description_en: "During a commute, spend 5 minutes deep breathing, observing the crowd inside without critique.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "გზაში ყოფნისას, გაასწორე წელში ხერხემალი, გააკეთე 5 ღრმა ჩასუნთქვა. შეეცადე მშვიდად, სიყვარულით უყურო გარშემო მყოფებს. დაწერე რეფლექსია.",
    fullInstructions_en: "Keep your spine tall. Take 5 deep breaths. Absorb the surroundings with patient benevolence. Document the mental state.",
    safetyRules: "გამოიჩინეთ უსაფრთხოება და ყურადღება მატარებლის ან ავტობუსის მოძრაობისას.",
    safetyRules_en: "Keep hands secure on vehicle handrails to prevent falling off during transit.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 2,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 5,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 5,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გაგიადვილდათ სიმშვიდის შენარჩუნება ხმაურში?",
    reflectionQuestion_en: "Did you easily find balance amidst standard engine clatter?",
    personalDevelopmentReason: "გარემო ხმაურთან შეგუება და მენტალური დაცვა.",
    personalDevelopmentReason_en: "Developing mental shields and noise tolerance indexes."
  },
  {
    id: "ch-sept-5",
    marathonId: "marathon-september",
    challengeNumber: 5,
    title: "რევოლუციური ჩაცმულობა",
    title_en: "Revolutionary Color Coordination",
    description: "შეუფერე ტანსაცმელს ერთი მკვეთრად გამორჩეული ფერადი აქსესუარი (მაგ: წითელი შარფი, ყვითელი ქუდი).",
    description_en: "Wear one highly saturated, bright accessory outside (e.g. bright yellow hat or red scarf).",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "გამოიყენე ფერები, რათა დაარღვიო ნაცრისფერი ყოველდღიურობა. იარე თავდაჯერებულად საჯარო სივრცეებში. ჩაწერე ვიდეო ან ფოტო.",
    fullInstructions_en: "Contrast the grey commute of autumn. Wear your vibrant wrap or hat with clean posture. Upload image/video proof.",
    safetyRules: "აქსესუარი უნდა იყოს უსაფრთხო და აკმაყოფილებდეს საზოგადოებრივ ეთიკას.",
    safetyRules_en: "The outfit must align with standard basic public decency rules.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 15,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 15,
    submissionType: "photo" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გრძნობდით თავს ყურადღების ცენტრში და როგორ გამკლავდით ამას?",
    reflectionQuestion_en: "Did you feel exposed, and how did you process the focus?",
    personalDevelopmentReason: "საკუთარ ვიზუალზე ყურადღების მიღება და კომფორტი.",
    personalDevelopmentReason_en: "Normalizing being noticed and embracing visual distinctness."
  },
  {
    id: "ch-sept-6",
    marathonId: "marathon-september",
    challengeNumber: 6,
    title: "თავდაჯერებული სიარულის მანერა",
    title_en: "The Runway Swagger Walk",
    description: "გაიარე 20 მეტრი თავდაჯერებული, ლამაზად გაზავებული 'სამოდელო' სიარულით და დააფიქსირე განცდა.",
    description_en: "Walk a 20-meter stretch with a highly expressive mock catwalk swagger posture.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "გასწორდი, ასწიე თავი, შეხედე წინ და იარე ისე, თითქოს პარიზის მოდის კვირეულზე იქნები. ჩაწერე შენი პროცესი ვიდეოზე.",
    fullInstructions_en: "Lift your chin, broaden shoulders, look forward, and walk like you lead a grand runway. Record a beautiful 15-second snippet.",
    safetyRules: "გააკეთეთ ეს უსაფრთხო საფეხმავლო ზონაში, მოერიდეთ დაბრკოლებებს.",
    safetyRules_en: "Catwalk on safe pavements away from any physical objects.",
    difficulty: "hard" as const,
    emotionalCourageLevel: 4,
    challengeCost: 20,
    completionReward: 40,
    publicBraveryBonus: 20,
    points: 40,
    acceptanceCost: 20,
    skipCost: 5,
    publicVideoBonus: 20,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "რა შეიცვალა შენს ხასიათში ხერხემლის გასწორების შემდეგ?",
    reflectionQuestion_en: "What shifted in your internal feelings when correcting your spine posture?",
    personalDevelopmentReason: "სხეულის ენის (power posing) გავლენა თვითშეფასებაზე.",
    personalDevelopmentReason_en: "Power posing connection to inner confidence and neurotransmitters."
  },
  {
    id: "ch-sept-7",
    marathonId: "marathon-september",
    challengeNumber: 7,
    title: "საჯარო კომპლიმენტი კონსულტანტს",
    title_en: "Loud Compliment to a Cashier",
    description: "მადლობის გადახდისას, უთხარი მოლარეს მისი სწრაფი მუშაობის ან ლამაზი ღიმილის შესახებ.",
    description_en: "When receiving change/receipt, convey a warm compliment to the cashier on their high efficiency.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "შოპინგის შემდეგ, თვალებში შეხედე მოლარეს და უთხარი: 'განსაკუთრებული მადლობა სწრაფი მომსახურებისთვის, თქვენ განწყობა ამიმაღლეთ!'. დაწერე კმაყოფილება.",
    fullInstructions_en: "Look into their eyes when checking out. Say 'Thanks for such rapid service, you really boosted my mood today!' Submit reflection.",
    safetyRules: "იყავით სრულიად კორექტული, თავაზიანი და უსაფრთხო.",
    safetyRules_en: "Remain highly professional and polite. Do not lock their window if others wait in line.",
    difficulty: "medium" as const,
    emotionalCourageLevel: 3,
    challengeCost: 15,
    completionReward: 30,
    publicBraveryBonus: 10,
    points: 30,
    acceptanceCost: 15,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "როგორ უპასუხა მან შენს სიტყვებს?",
    reflectionQuestion_en: "How did their facial expression morph?",
    personalDevelopmentReason: "ყოველდღიური სოციალური ბარიერების მსხვრევა და კეთილგანწყობა.",
    personalDevelopmentReason_en: "Melting day-to-day transaction barriers and sharing positive vibes."
  },
  {
    id: "ch-sept-8",
    marathonId: "marathon-september",
    challengeNumber: 8,
    title: "კომპლექსების წერტილი",
    title_en: "Insecurities Spotter",
    description: "ამოიცანი შენი 1 აქტიური სოციალური შეზღუდვა და ახსენი, როგორ მუშაობ მის დაძლევაზე.",
    description_en: "Locate one of your active mental defense layers and write a summary on dissolving it.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "ჩამოაყალიბე წერილობით: 'მე ზოგჯერ მეშინია უარის თქმის, მაგრამ სწორედ ამ საზღვრის დაცვაზე ვიწყებ მუშაობას'. გააზიარე რეფლექსია.",
    fullInstructions_en: "State cleanly: 'I sometimes fear rejecting others or expressing boundaries. I am learning to establish them politely'. Share your thoughts.",
    safetyRules: "ეს არის ანალიტიკური ტექნიკა, იყავით გულწრფელი.",
    safetyRules_en: "This is a cognitive analysis, keep it self-compassionate.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 2,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 5,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 5,
    submissionType: "reflection" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გეხმარება თუ არა პრობლემის სახელდება მის მინიმუმამდე დაყვანაში?",
    reflectionQuestion_en: "Does labelling a problem reduce its immediate scale over you?",
    personalDevelopmentReason: "კოგნიტურ-ბიჰევიორული თვითანალიზი.",
    personalDevelopmentReason_en: "Applying cognitive-behavioral self-assessment to decrease blockades."
  },
  {
    id: "ch-sept-9",
    marathonId: "marathon-september",
    challengeNumber: 9,
    title: "ჩემი ძველი ფოტოს მიღება",
    title_en: "Embracing My Old Self Photo",
    description: "მოძებნე შენი ძველი ფოტო (მაგ: ბავშვობის ან მოზარდობის) და მიწერე საკუთარ თავს თბილი სიტყვები.",
    description_en: "Find any older photo of yourself (childhood/adolescence) and write a sweet paragraph of acceptance.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "განათავსე შენი ძველი ფოტო გვერდზე. ჩაიწერე მოკლე ხმოვანი განმარტება ან დაწერე: 'შენ მაშინ ბევრს ნერვიულობდი, მაგრამ მე მინდა იცოდე, რომ ყველაფერს კარგად გაართვი თავი'. გააზიარე ფოტო ჩანაწერით.",
    fullInstructions_en: "Place an old image of yourself nearby. Tell them: 'You used to worry excessively back then, but look how beautiful and resilient you grew up to be!'. Share this warm act.",
    safetyRules: "გაზიარება უნდა იყოს სრულიად კომფორტული და უსაფრთხო თქვენთვის.",
    safetyRules_en: "Make sure you only upload an image that you feel comfortable conveying.",
    difficulty: "easy" as const,
    emotionalCourageLevel: 1,
    challengeCost: 10,
    completionReward: 20,
    publicBraveryBonus: 10,
    points: 20,
    acceptanceCost: 10,
    skipCost: 5,
    publicVideoBonus: 10,
    submissionType: "photo" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "შეამჩნიე თუ არა, რამდენად ნაზად გიყურებს ის ბავშვი ფოტოდან?",
    reflectionQuestion_en: "Did you feel an immediate rush of self-compassion?",
    personalDevelopmentReason: "წარსული ვერსიების რეინტეგრაცია და თანაგრძნობა.",
    personalDevelopmentReason_en: "Re-integrating historic versions of the self with profound compassion."
  },
  {
    id: "ch-sept-10",
    marathonId: "marathon-september",
    challengeNumber: 10,
    title: "მარათონის ვარსკვლავური გამოსვლა",
    title_en: "The Starry Marathon Exit Speech",
    description: "ჩაწერე 1-წუთიანი შეჯამება, სადაც აღწერ თუ როგორ შეიცვალე ამ 4 თვის განმავლობაში.",
    description_en: "Record a glorious 1-minute video summary detailing how your social courage expanded during this marathon.",
    preview_ka: "ეს არის გამოწვევის მოკლე აღწერა. სრული ინსტრუქცია გამოჩნდება გამოწვევის მიღების შემდეგ.",
    preview_en: "This is a short preview of the challenge. Full instructions will appear after accepting the challenge.",
    fullInstructions: "დაჯექი კამერის წინ, გაისწორე მხრები. ამაყად ჩამოთვალე შენი გამარჯვებები, შენს მიერ შესრულებული სამუშაო და გადაუხადე მადლობა შენს თავსა და სხვა მოთამაშეებს.",
    fullInstructions_en: "Sit in front of the camera with highly confident posture. Summarize your top 3 milestone accomplishments, express gratitude to yourself and the community, and celebrate your victory.",
    safetyRules: "გამოწვევა სრულდება მხიარული ემოციით და გამამხნევებელი ტონით.",
    safetyRules_en: "Deliver in a happy, highly empowering tone.",
    difficulty: "hard" as const,
    emotionalCourageLevel: 5,
    challengeCost: 30,
    completionReward: 60,
    publicBraveryBonus: 30,
    points: 60,
    acceptanceCost: 30,
    skipCost: 5,
    publicVideoBonus: 30,
    submissionType: "video" as const,
    status: "active" as const,
    aiGenerated: false,
    approvedByAdmin: true,
    reflectionQuestion: "გრძნობ თუ არა, რომ 'ბიფურკაცია' მართლაც შენი გზის გაყოფის მომენტი იყო?",
    reflectionQuestion_en: "Do you truly feel that Bifurcation was a turning point for your personal development?",
    personalDevelopmentReason: "კოგნიტური კონსოლიდაცია და თვითეფექტურობის გამჯობინება.",
    personalDevelopmentReason_en: "Consolidating confidence outcomes and confirming high self-efficacy."
  }
];
